name: suite
description: Flutter Application Suites from Udemy Course
authors:
  - Htin Linn Zaw (htinlinnzaw.dev@gmail.com)
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: "2.9.0-18.0.dev.flutter-6b630c3719"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true